ChECalc = [

    { "text": 'Wine making involves a series of very complex reactions most of which are performed by microorganisms. The starting concentration of sugars determines the final alcohol content and sweetness of the wine. The specific gravity of the starting stock is therefore adjusted to achieve desired quality of wine. A starting stock solution has a specific gravity of 1.075 and contains 12.7 wt% sugar. If all the sugar is assumed to be C₁2H22011, determine kg sugar/ kg H₂0  ',  "options": ['A. 0.286', 'B. 0.039', 'C. 0.145', 'D.  0.327'], "correct": 2}, 
    { "text": 'Wine making involves a series of very complex reactions most of which are performed by microorganisms. The starting concentration of sugars determines the final alcohol content and sweetness of the wine. The specific gravity of the starting stock is therefore adjusted to achieve desired quality of wine. A starting stock solution has a specific gravity of 1.075 and contains 12.7 wt% sugar. If all the sugar is assumed to be C₁2H22011, determine  lb solution /ft3 solution',  "options": ['A. 67.1', 'B. 39.2', 'C. 50.5', 'D. 48.6'], "correct": 0}, 
    { "text": 'Wine making involves a series of very complex reactions most of which are performed by microorganisms. The starting concentration of sugars determines the final alcohol content and sweetness of the wine. The specific gravity of the starting stock is therefore adjusted to achieve desired quality of wine. A starting stock solution has a specific gravity of 1.075 and contains 12.7 wt% sugar. If all the sugar is assumed to be C₁2H22011, determine  g sugar/L solution',  "options": ['A. 202', 'B. 136', 'C. 295', 'D. 144'], "correct": 1}, 

    { "text": 'Two aqueous sulfuric acid solutions containing 20 wt% H2SO, (SG=1.139) and 60 wt% H₂SO (SG=1.498) are mixed to form a 4 M solution (SG-1.213).  Calculate the mass fraction of sulfuric acid in the product solution.',  "options": ['A. 0.105', 'B.  0.667', 'C.  0.323', 'D. 0.548'], "correct": 2}, 
    { "text": 'Two aqueous sulfuric acid solutions containing 20 wt% H2SO, (SG=1.139) and 60 wt% H₂SO (SG=1.498) are mixed to form a 4 M solution (SG-1.213).  Calculate the feed ratio (liters 20% solution per liter 60% solution)',  "options": ['A. 2.96', 'B. 3.08', 'C.  1.75', 'D. 4.51'], "correct": 0}, 
    { "text": 'Two aqueous sulfuric acid solutions containing 20 wt% H2SO, (SG=1.139) and 60 wt% H₂SO (SG=1.498) are mixed to form a 4 M solution (SG-1.213).  What feed rate of the 60% solution (L/hr) would be required to produce 1250 kg/h of the product.',  "options": ['A. 986 L/h', 'B.  257 L/h', 'C. 110 L/h', 'D. 462 L/h'], "correct": 1}, 

    { "text": 'If 1 L of ethyl alcohol is mixed with 1 L of water at 20°C. How many kilograms of solution result?',  "options": ['A. 1.85 kg', 'B.  2.06 kg', 'C. 1.79 kg', 'D. 2.11 kg'], "correct": 2}, 
    { "text": 'If 1 L of ethyl alcohol is mixed with 1 L of water at 20°C. How many liters?',  "options": ['A. 1.93 L', 'B. 1.88 L', 'C. 2.00 L', 'D. 2.15 L'], "correct": 0}, 

    { "text": 'A supplier shipped a material for chicken feed with the following analytical report: protein - 22%, triglyceride - 8%, moisture - 10%. During transport moisture was picked up by the material; the later analytical report showed 14% moisture. Based on the latest report, recalculate the % triglyceride.',  "options": ['A.  21.02%', 'B.  39.33%', 'C. 7.64%', 'D. 14.65%'], "correct": 2}, 
   
    { "text": 'An evaporator is fed continuously with 25 MT/h\r\nof a solution consisting of 10% NaOH, 10% NaCl,\r\nand 80% H₂0. During evaporation, water is\r\nboiled off, and salt precipitates as crystals,\r\nwhich are settled and removed from the\r\nremaining liquor. The concentrated liquor\r\nleaving the evaporator contains 50% NaOH, 2%\r\nNaCl and 48% H₂0. Calculate the kg of water evaporated per\r\nhour',  "options": ['A. 19300', 'B. 18500', 'C. 17600', 'D. 16200'], "correct": 2}, 
    { "text": 'An evaporator is fed continuously with 25 MT/h\r\nof a solution consisting of 10% NaOH, 10% NaCl,\r\nand 80% H₂0. During evaporation, water is\r\nboiled off, and salt precipitates as crystals,\r\nwhich are settled and removed from the\r\nremaining liquor. The concentrated liquor\r\nleaving the evaporator contains 50% NaOH, 2%\r\nNaCl and 48% H₂0. Calculate the kg salt precipitated per\r\nhour\r\n',  "options": ['A. 2400', 'B. 3500', 'C. 1100', 'D. 4700'], "correct": 0}, 
    { "text": 'An evaporator is fed continuously with 25 MT/h\r\nof a solution consisting of 10% NaOH, 10% NaCl,\r\nand 80% H₂0. During evaporation, water is\r\nboiled off, and salt precipitates as crystals,\r\nwhich are settled and removed from the\r\nremaining liquor. The concentrated liquor\r\nleaving the evaporator contains 50% NaOH, 2%\r\nNaCl and 48% H₂0. Calculate the kg of concentrated liquor\r\nproduced per hour',  "options": ['A. 4000', 'B. 3000', 'C. 6000', 'D. 5000'], "correct": 3}, 

    { "text": 'Ten kilograms each of salts A and B are\r\ndissolved in 50 kg of water. The solubility of\r\nA in water is 1 kg per kg water and that of B\r\nis 0.5 kg per kg of water. The solution is\r\nheated to evaporate water. When the\r\nconcentration of the solution reaches the\r\nsaturation concentration of any salt, further\r\nevaporation results in the crystallization of\r\nthat salt. If 70% of the water that is\r\noriginally present in the solution is driven\r\noff by evaporation, determine the following: The weight of the final solution',  "options": ['A. 46.5', 'B. 28.5', 'C. 11.5', 'D. 32.5'], "correct": 3}, 
    { "text": 'Ten kilograms each of salts A and B are\r\ndissolved in 50 kg of water. The solubility of\r\nA in water is 1 kg per kg water and that of B\r\nis 0.5 kg per kg of water. The solution is\r\nheated to evaporate water. When the\r\nconcentration of the solution reaches the\r\nsaturation concentration of any salt, further\r\nevaporation results in the crystallization of\r\nthat salt. If 70% of the water that is\r\noriginally present in the solution is driven\r\noff by evaporation, determine the following: The weight of the crystals formed',  "options": ['A. 2.5', 'B. 5.5', 'C. 0', 'D. 1.5'], "correct": 0}, 

    { "text": '1200 lb of barium nitrate is dissolved in sufficient water to\r\nform a saturated solution at 90°C. Assuming that 5% of the\r\nweight of the original solution is lost through evaporation\r\ncalculate the crop of crystals obtained when cooled at 20°C.\r\nSolubility data for barium nitrate at 90°C is 30.6% wt and 8.6\r\nwt% at 20°C. ',  "options": ['A. 952.4 lbs', 'B. 970 lbs', 'C.  962.4 lbs', 'D. 980 lbs'], "correct": 2}, 

    { "text": 'What is the theoretical yield of crystals which may be\r\nobtained by cooling a solution containing 1000 kg of sodium\r\nsulfate (mw = 142 kg/kmol) in 5000 kg water to 283 K? The\r\nsolubility of sodium sulfate at 283 K is 9 kg anhydrous salt\r\n100 kg water and the deposited crystals will consist of\r\ndecahydrate. It may be assumed that 2% of the water will be\r\nlost by evaporation during cooling. ',  "options": ['A. 4469.17 kg', 'B.  250 kg', 'C. 6000 kg', 'D. 1430.83 kg'], "correct": 3}, 

    # Lecture 2

    { "text": 'Oil is extracted from seeds by leaching with organic solvents.\r\nSoybean seeds containing 20% oil, 65% inert solids and 15% water\r\nare leached with hexane and after extraction the solid residue is\r\nremoved from the solution of oil in hexane. The residue analyzed\r\n1.0% oil, 88% inert cake and 11% water. What percent of oil is\r\nrecovered? ',  "options": ['A. 90%', 'B. 82%', 'C. 96%', 'D. 87%'], "correct": 2}, 

    { "text": 'Acetone is recovered from an acetone-air mixture\r\ncontaining 25% (volume) acetone by scrubbing with water.\r\nAssuming that air is insoluble in water, determine the percent\r\nof acetone in the entering gas that is absorbed if the gas\r\nleaving the scrubber analyzes 5% acetone. ',  "options": ['A. 96%', 'B. 84%', 'C. 65%', 'D.  73%'], "correct": 1}, 

    { "text": 'An equimolar mixture of benzene and toluene is\r\nsubjected to a single batch distillation. Distillation is\r\ndiscontinued when 60% of the benzene in the feed is\r\ndistilled. At this instance the bottom product when\r\nanalyzed shows benzene to be 36.4% by mole. In the\r\ndistillate the mole% of benzene is ',  "options": ['A. 58.1', 'B. 66.6', 'C. 54.7', 'D. 33.6'], "correct": 1}, 

    { "text": ' In the azeotropic distillation of an ethanol-water solution, a feed\r\nmixture containing 95.6% alcohol is mixed with pure benzene and\r\ndistilled. The benzene forms a ternary azeotrope with alcohol-water\r\nwith a composition of 74.1% benzene, 7.4% water and 18.5% alcohol,\r\nwhich is distilled over as the overhead product. Absolute alcohol is\r\nobtained as the residue product. Determine the quantity of benzene\r\nrequired for producing 100 kg of absolute alcohol. ',  "options": ['A. 48 kg', 'B. 74 kg', 'C. 66 kg', 'D.  52 kg'], "correct": 3}, 

    { "text": ' One hundred pounds of solution containing 80 wt% Na2SO\r\nmust be obtained by evaporating a dilute solution using\r\ndouble effect evaporator. If the evaporator from the 2nd effect\r\nis 60% of that coming from the first effect and the concentrate\r\nof the first effect contains 1 lb Na₂SO per pound of water.\r\nCalculate for the composition of the feed. ',  "options": ['A. 69% Na₂SO4', 'B.  55% Na₂SO4', 'C.  45% Na₂SO4', 'D. 31% Na₂SO4'], "correct": 3}, 

    { "text": 'One drier will dry a material from 45% moisture (wb) to\r\n20% moisture (db) from here the material enters another drier\r\nwhere the H20 content is further reduced to give a final\r\nproduct weighing 1000 kg. If the total evaporation from both\r\ndriers is 800 kg, the moisture of the final product is ',  "options": ['A. 5%', 'B. 3%', 'C. 2%', 'D. 1%'], "correct": 3}, 

    { "text": 'An aqueous solution containing 15%\r\nNaOH and 0.5% NaCl is concentrated at\r\na rate of 100 kg/min in an evaporator.\r\nThe concentrated solution is then\r\nmixed with 2000 kg of aqueous NaOH\r\nsolution in a mixer. At the end of one\r\nhour a sample is collected from the\r\nmixer and analyzed. The analysis\r\nshows 40% NaOH and 0.8574% NaCl.\r\nCalculate the following:\r\n The concentration of the original\r\nsolution in the receiver\r\n',  "options": ['A.  32% NaOH', 'B. 25% NaOH', 'C. 40% NaOH', 'D. 56% NaOH'], "correct": 1}, 
    { "text": 'An aqueous solution containing 15%\r\nNaOH and 0.5% NaCl is concentrated at\r\na rate of 100 kg/min in an evaporator.\r\nThe concentrated solution is then\r\nmixed with 2000 kg of aqueous NaOH\r\nsolution in a mixer. At the end of one\r\nhour a sample is collected from the\r\nmixer and analyzed. The analysis\r\nshows 40% NaOH and 0.8574% NaCl.\r\nCalculate the following:\r\n The mass of water (in kilograms)\r\nevaporated in one hour',  "options": ['A. 3200 kg', 'B. 5100 kg', 'C. 4500 kg', 'D.  6600 kg'], "correct": 2}, 

    { "text": 'For the preparation of potassium nitrate, 10000\r\nkg/h of a 20% KNO3 solution is mixed with a\r\nrecycle stream and sent to an evaporator. The\r\nrate of evaporation is 1.5 times the rate of\r\nintroduction of recycle stream. The\r\nconcentrated solution leaving the evaporator\r\ncontains 50% KNO3. This is admitted to the\r\ncrystallizer which yields crystals containing 5%\r\nwater. At the crystallization temperature the\r\nsolubility is 50 kg/100 kg of water. The major\r\npart of the mother liquor leaving the\r\ncrystallizer is returned to the evaporator as\r\nrecycle. Calculate the following:\r\n The concentration of KNO3 in the streamentering the evaporator',  "options": ['A. 33%', 'B. 25%', 'C. 16%', 'D. 40%'], "correct": 1}, 
    { "text": 'For the preparation of potassium nitrate, 10000\r\nkg/h of a 20% KNO3 solution is mixed with a\r\nrecycle stream and sent to an evaporator. The\r\nrate of evaporation is 1.5 times the rate of\r\nintroduction of recycle stream. The\r\nconcentrated solution leaving the evaporator\r\ncontains 50% KNO3. This is admitted to the\r\ncrystallizer which yields crystals containing 5%\r\nwater. At the crystallization temperature the\r\nsolubility is 50 kg/100 kg of water. The major\r\npart of the mother liquor leaving the\r\ncrystallizer is returned to the evaporator as\r\nrecycle. Calculate the following:\r\n The rate of production of crystals',  "options": ['A. 3925', 'B. 2007', 'C. 1588', 'D. 4610'], "correct": 1}, 
    { "text": 'For the preparation of potassium nitrate, 10000\r\nkg/h of a 20% KNO3 solution is mixed with a\r\nrecycle stream and sent to an evaporator. The\r\nrate of evaporation is 1.5 times the rate of\r\nintroduction of recycle stream. The\r\nconcentrated solution leaving the evaporator\r\ncontains 50% KNO3. This is admitted to the\r\ncrystallizer which yields crystals containing 5%\r\nwater. At the crystallization temperature the\r\nsolubility is 50 kg/100 kg of water. The major\r\npart of the mother liquor leaving the\r\ncrystallizer is returned to the evaporator as\r\nrecycle. Calculate the following:\r\n The flow rate of recycle stream in kg/h',  "options": ['A. 5143', 'B. 4531', 'C. 1354', 'D. 3415'], "correct": 0}, 

    { "text": 'Fresh air containing 4 mol% water vapor is to\r\nbe cooled and dehumidified to a water content\r\nof 1.70 mol% H₂O. A stream of fresh air is\r\ncombined with a recycle stream of previously\r\ndehumidified air and passed through the cooler.\r\nThe blended stream entering the unit contains\r\n2.3 mol% H₂0. In the air conditioner, some of the\r\nwater in the feed stream is condensed and\r\nremoved as liquid. A fraction of the\r\ndehumidified air leaving the cooler is recycled\r\nand the remainder is delivered to a room.\r\nTaking 100 mol of dehumidified air delivered to\r\nthe room as a basis of calculation, calculate the\r\nfollowing: The moles of fresh feed',  "options": ['A. 115 mol', 'B.  126 mol', 'C.  102 mol', 'D. 133 mol'], "correct": 2}, 
    { "text": 'Fresh air containing 4 mol% water vapor is to\r\nbe cooled and dehumidified to a water content\r\nof 1.70 mol% H₂O. A stream of fresh air is\r\ncombined with a recycle stream of previously\r\ndehumidified air and passed through the cooler.\r\nThe blended stream entering the unit contains\r\n2.3 mol% H₂0. In the air conditioner, some of the\r\nwater in the feed stream is condensed and\r\nremoved as liquid. A fraction of the\r\ndehumidified air leaving the cooler is recycled\r\nand the remainder is delivered to a room.\r\nTaking 100 mol of dehumidified air delivered to\r\nthe room as a basis of calculation, calculate the\r\nfollowing: The moles of water condensed',  "options": ['A.  0.8 mol', 'B. 1.0 mol', 'C.  2.4 mol', 'D. 3.3 mol'], "correct": 2}, 
    { "text": 'Fresh air containing 4 mol% water vapor is to\r\nbe cooled and dehumidified to a water content\r\nof 1.70 mol% H₂O. A stream of fresh air is\r\ncombined with a recycle stream of previously\r\ndehumidified air and passed through the cooler.\r\nThe blended stream entering the unit contains\r\n2.3 mol% H₂0. In the air conditioner, some of the\r\nwater in the feed stream is condensed and\r\nremoved as liquid. A fraction of the\r\ndehumidified air leaving the cooler is recycled\r\nand the remainder is delivered to a room.\r\nTaking 100 mol of dehumidified air delivered to\r\nthe room as a basis of calculation, calculate the\r\nfollowing: The moles of dehumidified air recycled',  "options": ['A. 270 mol', 'B. 290 mol', 'C.  280 mol', 'D. 260 mol'], "correct": 1}, 

    { "text": 'Fresh orange juice contains 12% (by weight) solids\r\nand the rest water 90% of the fresh juice is sent to an\r\nevaporator to remove water and subsequently mixed\r\nwith the remaining 10% of fresh juice. The resultant\r\nproduct contains 40% solids. The kg of water removed\r\nfrom 1 kg fresh juice is ',  "options": ['A. 0.4', 'B. 0.6', 'C. 0.5', 'D. 0.7'], "correct": 3}, 

    { "text": 'A process stream contains 4% (weight) salt and the rest\r\nwater. This is prepared by passing a part of pure water stream\r\nthrough a saturator containing the salt. The solution leaving\r\nthe saturator containing 20% salt is mixed with the pure water\r\nbypassed to get the process stream. What fraction of the pure\r\nwater available is to be passed through the saturator? ',  "options": ['A.  0.23', 'B. 0.17', 'C. 0.29', 'D. 0.10'], "correct": 1}, 

    { "text": 'A limestone analysis: CaCO3 - 92.89%,\r\nMgC03 - 5.41% and unreactive - 1.70%.\r\nBy heating the limestone, you recover\r\noxides that together known as lime: How many pounds of calcium oxide\r\ncan be made from 1 ton of limestone?',  "options": ['A. 1041 lb', 'B. 3567 lb', 'C. 2348 lb', 'D. 4020 lb'], "correct": 0}, 
    { "text": 'A limestone analysis: CaCO3 - 92.89%,\r\nMgC03 - 5.41% and unreactive - 1.70%.\r\nBy heating the limestone, you recover\r\noxides that together known as lime: How many pounds of CO2 can be\r\nrecovered per lb of limestone?',  "options": ['A. 0.33', 'B. 0.11', 'C.  0.22', 'D. 0.44'], "correct": 3}, 
    { "text": 'A limestone analysis: CaCO3 - 92.89%,\r\nMgC03 - 5.41% and unreactive - 1.70%.\r\nBy heating the limestone, you recover\r\noxides that together known as lime: How many pounds of limestone are\r\nneeded to make 1 ton of lime?',  "options": ['A. 3100', 'B. 3890', 'C. 3550', 'D. 3760'], "correct": 2}, 

    { "text": 'The synthesis of ammonia proceeds\r\naccording to the following reaction:\r\nN2+ 3 H2→ 2 NH3\r\nIn a given plant, 4202 lb of nitrogen and\r\n1046 lb of hydrogen are fed to the synthesis\r\nreactor per hour. Production of pure\r\nammonia from this reactor is 3060 lb per\r\nhour.\r\n What is the limiting reactant?',  "options": ['A. N₂', 'B. H₂', 'C. both N₂ and H₂', 'D. NH3'], "correct": 0}, 
    { "text": 'The synthesis of ammonia proceeds\r\naccording to the following reaction:\r\nN2+ 3 H2→ 2 NH3\r\nIn a given plant, 4202 lb of nitrogen and\r\n1046 lb of hydrogen are fed to the synthesis\r\nreactor per hour. Production of pure\r\nammonia from this reactor is 3060 lb per\r\nhour.\r\n What is the percent excess reactant?',  "options": ['A. 12%', 'B.  16%', 'C. 18%', 'D.  10%'], "correct": 1}, 
    { "text": 'The synthesis of ammonia proceeds\r\naccording to the following reaction:\r\nN2+ 3 H2→ 2 NH3\r\nIn a given plant, 4202 lb of nitrogen and\r\n1046 lb of hydrogen are fed to the synthesis\r\nreactor per hour. Production of pure\r\nammonia from this reactor is 3060 lb per\r\nhour.\r\n What is the percent conversion obtained\r\nbased on the limiting reactant?',  "options": ['A. 50%', 'B. 60%', 'C.  70%', 'D. 80%'], "correct": 1}, 

    { "text": 'A barytes composed of 100 percentBaSO4 is fused with carbon in the formof coke containing 6% ash (which isinfusible). The composition of the fusionmass is BaSO 11.1%, BaS 72.8%, C 13.9%,  Ash 2.2%,  Reaction: BaSO+4 C→ BaS + 4 CO. Find the excess reactant.',  "options": ['A. C', 'B. BaS04', 'C. CO', 'D. BaS'], "correct": 0}, 
    { "text": 'A barytes composed of 100 percentBaSO4 is fused with carbon in the formof coke containing 6% ash (which isinfusible). The composition of the fusionmass is BaSO 11.1%, BaS 72.8%, C 13.9%,  Ash 2.2%,  Reaction: BaSO+4 C→ BaS + 4 CO. Find the percent excess reactant.',  "options": ['A. 44.8%', 'B. 38.9%', 'C. 50.6%', 'D.  66.7%'], "correct": 2}, 
    { "text": 'A barytes composed of 100 percentBaSO4 is fused with carbon in the formof coke containing 6% ash (which isinfusible). The composition of the fusionmass is BaSO 11.1%, BaS 72.8%, C 13.9%,  Ash 2.2%,  Reaction: BaSO+4 C→ BaS + 4 CO. What is the degree of completion of\r\nthe reaction?',  "options": ['A. 0.6', 'B. 0.7', 'C. 0.8', 'D. 0.9'], "correct": 3}, 

    { "text": 'Pure ethanol vapor is fed to a reactor packed with aluminacatalyst, at the rate of 100 kmole/hr. The reactor products compriseethylene: 95 kmole/hr, water vapor: 97.5 kmole/hr and diethyl ether:2.5 kmole/hr. The reactions occurring can be represented by:C2H5OH C2H4 + H₂O &  2 C2H5OH → C2H5 - O - C2H5 + H₂O. The percent conversion of ethanol in the reactor is ',  "options": ['A. 100', 'B. 95', 'C. 97.5', 'D.  2.5'], "correct": 0}, 

    { "text": 'In the Deacon process for the manufacture of\r\nchlorine, HCl and O₂ react to form Cl₂ and H₂0. Sufficient\r\nair is fed to provide 35% excess oxygen and the\r\nfractional conversion of HCl is 85%. Calculate the mole\r\nfraction of water in the product stream. ',  "options": ['A. 0.18', 'B. 0.12', 'C. 0.10', 'D.  0.15'], "correct": 0}, 

    { "text": 'Acrylonitrile is produced in thereaction of propylene, ammonia andoxygen:C3H + NH3 + 3/2 0₂ → C3H3N + 3 H2O The feed contains 10 mole % propylene,12 mole% ammonia, and 78% air. A fractional conversion of 30% of the limiting reactant is achieved. Taking 100 mol of feed as basis, determine the following: The percentage by which of the\r\nreactants in excess',  "options": ['A. 24%, 6.2%', 'B. 28%, 7.5%', 'C. 25%, 8.5%', 'D. 20%, 9.2%'], "correct": 3}, 
    { "text": 'Acrylonitrile is produced in thereaction of propylene, ammonia andoxygen:C3H + NH3 + 3/2 0₂ → C3H3N + 3 H2O The feed contains 10 mole % propylene,12 mole% ammonia, and 78% air. A fractional conversion of 30% of the limiting reactant is achieved. Taking 100 mol of feed as basis, determine the following: The mole% of water in the product\r\ngas',  "options": ['A. 6%', 'B.  7%', 'C. 5%', 'D. 9%'], "correct": 3}, 

    { "text": 'TiCl4, can be formed by reacting titaniumdioxide (TiO,) with hydrochloric acid. TiO₂is available as an ore containing 78 % TiO2and 22% inerts. The HCL is available as 45wt% solution (the balance is water). Theper pass conversion of TiO₂ is 75 %. TheHCl is fed into the reactor in 20% excessbased on the reaction. Pure unreacted TiO2 is recycled back to mix with the Ti02 feed. TiO2+ 4 HCL→ TiCl4 + 2H₂0For 1 kg of TiCl4 produced, determine: The kg ofTiO2 ore fed.',  "options": ['A. 0.26', 'B.  0.54', 'C. 2.05', 'D. 1.33'], "correct": 1}, 
    { "text": 'TiCl4, can be formed by reacting titaniumdioxide (TiO,) with hydrochloric acid. TiO₂is available as an ore containing 78 % TiO2and 22% inerts. The HCL is available as 45wt% solution (the balance is water). Theper pass conversion of TiO₂ is 75 %. TheHCl is fed into the reactor in 20% excessbased on the reaction. Pure unreacted TiO2 is recycled back to mix with the Ti02 feed. TiO2+ 4 HCL→ TiCl4 + 2H₂0For 1 kg of TiCl4 produced, determine:  The kg of 45 wt % HCl solution fed.',  "options": ['A. 0.26', 'B. 0.54', 'C. 2.05', 'D.  1.33'], "correct": 2}, 
    { "text": 'TiCl4, can be formed by reacting titaniumdioxide (TiO,) with hydrochloric acid. TiO₂is available as an ore containing 78 % TiO2and 22% inerts. The HCL is available as 45wt% solution (the balance is water). Theper pass conversion of TiO₂ is 75 %. TheHCl is fed into the reactor in 20% excessbased on the reaction. Pure unreacted TiO2 is recycled back to mix with the Ti02 feed. TiO2+ 4 HCL→ TiCl4 + 2H₂0For 1 kg of TiCl4 produced, determine:  The ratio of recycle stream to fresh\r\nTiO2 ore (in kg).',  "options": ['A. 0.26', 'B. 0.54', 'C. 2.05', 'D.  1.33'], "correct": 0}, 

    { "text": 'Propane is dehydrogenated to formpropylene in a catalytic reactor. The process is to be designed for a 95% overall conversion of propane. Thereaction products are separated into twostreams: the first, which contains H₂, СзH6 and 0.555% of the propane that leaves thereactor, is taken off as a product; thesecond stream, which contains thebalance of the unreacted propane and 5%of the propylene in the first stream, is recycled to the reactor. Calculate the ratio of moles recycled /\r\nmole fresh feed',  "options": ['A.  1.2', 'B. 6.8', 'C. 2.5', 'D. 9.0'], "correct": 3}, 
    { "text": 'Propane is dehydrogenated to formpropylene in a catalytic reactor. The process is to be designed for a 95% overall conversion of propane. Thereaction products are separated into twostreams: the first, which contains H₂, СзH6 and 0.555% of the propane that leaves thereactor, is taken off as a product; thesecond stream, which contains thebalance of the unreacted propane and 5%of the propylene in the first stream, is recycled to the reactor. What is the single-pass conversion?',  "options": ['A. 9.6%', 'B. 13.5%', 'C.  25.0%', 'D. 38.2'], "correct": 0}, 

    # Lecture 3

    { "text": 'Pure dry hydrogen gas is burned\r\ncompletely using 100% excess air.\r\nDetermined the % 02 in the flue gases in\r\nthe complete analysis. ',  "options": ['A. 4.5%', 'B. 11.73%', 'C. 9.5%', 'D. 0%'], "correct": 2}, 

    { "text": 'A fuel containing 75% ethane and 25% propane is burned with dry air. All the Н₂\r\nburns to H₂0 and the CO2 to CO ratio is 10:1. Fifteen% excess air is supplied.\r\nCalculate: Percent CO in the Orsat analysis of stack gas',  "options": ['A. 1.04%', 'B.  2.18%', 'C. 5.33%', 'D. 4.27%'], "correct": 0}, 
    { "text": 'A fuel containing 75% ethane and 25% propane is burned with dry air. All the Н₂\r\nburns to H₂0 and the CO2 to CO ratio is 10:1. Fifteen% excess air is supplied.\r\nCalculate: Percent CO in the complete analysis of stack gas',  "options": ['A. 0.65%', 'B. 0.33%', 'C. 0.89%', 'D. 0.99%'], "correct": 2}, 

    { "text": 'Orsat analysis of the stack gas from the combustion of a gaseous mixture of\r\nacetylene and methane shows 9.82% CO₂, 1.37% CO, 0.69% H2, 5.43% 02 and\r\n82.69% N₂. Determine: The % excess air',  "options": ['A. 15%', 'B. 20%', 'C.  10%', 'D. 25%'], "correct": 3}, 
    { "text": 'Orsat analysis of the stack gas from the combustion of a gaseous mixture of\r\nacetylene and methane shows 9.82% CO₂, 1.37% CO, 0.69% H2, 5.43% 02 and\r\n82.69% N₂. Determine:  The % mol CH, in the gaseous fuel',  "options": ['A. 50%', 'B. 30%', 'C. 40%', 'D. 60%'], "correct": 3}, 

    { "text": 'A pure saturated hydrocarbon is burnt with excess air. Orsat analysis of the\r\nstack gas shows 7.9% CO2, 1.18% CO, 0.24% H2, 5.25% 02, and 85.43% N₂. Air is\r\nsubstantially dry. The stack gases leave at 750 mmHg pressure. Calculate:\r\n The % excess air',  "options": ['A. 25%', 'B. 34%', 'C.  18%', 'D. 44%'], "correct": 0}, 
    { "text": 'A pure saturated hydrocarbon is burnt with excess air. Orsat analysis of the\r\nstack gas shows 7.9% CO2, 1.18% CO, 0.24% H2, 5.25% 02, and 85.43% N₂. Air is\r\nsubstantially dry. The stack gases leave at 750 mmHg pressure. Calculate:\r\n The formula of the hydrocarbon',  "options": ['A.  CH4', 'B.  C2H6', 'C.  C3H8', 'D.  C4H10'], "correct": 0}, 

    { "text": 'In a single stage extraction process, 10 kg of pure solvent S (containing no solute A) is mixed with 30kg of feed F containing A at a mass fraction xf = 0.2. The mixture splits into an extract phase E and a raffinate phase R containing A at xe = 0.5 and xr = 0.05 respectively. The total mass of the extract phase is (in kg) ',  "options": ['A. 6.89', 'B. 8.89', 'C.  10', 'D.  8.25'], "correct": 1}, 
    
    { "text": 'A hydrocarbon gas was completely combusted and produced 3.3 g CO2 and 1.125 g H2O. What is the empirical formula of the gas ',  "options": ['A. CH', 'B. CH3', 'C. C2H5', 'D. C3H5'], "correct": 3}, 

    { "text": 'Methane is burned completely with theoretical air. What is the air-fuel volume ratio ',  "options": ['A. 2:1', 'B. 9.52:1', 'C. 4.76:1', 'D. 19.04:1'], "correct": 1}, 

    { "text": '6 g of carbon is burnt with an amount of air containing 18 g oxygen. The product contains 16.5 g CO2 and 2.8 g CO besides other constituents. What is the degree of conversion on the basis of disappearance of limiting reactant ',  "options": ['A. 100%', 'B. 75%', 'C. 95%', 'D. 20%'], "correct": 2}, 

    { "text": 'The burning of pure butane with excess air\r\ngives a stack gas which analyzes 11.55% CO₂ on a\r\ndry basis. Assuming complete combustion,\r\ncalculate the % excess air ',  "options": ['A. 16%', 'B. 20%', 'C. 11%', 'D. 23%'], "correct": 1}, 

    { "text": 'A furnace burns a fuel oil containing 82% carbon,\r\n17% hydrogen and 1% sulfur using 10% excess air.\r\nAssuming that the combustion of C to CO₂ is only 90%\r\ncomplete and that all the sulfur is burnt to SO2\r\ncalculate the %CO₂ in the analysis of flue gas. ',  "options": ['A. 6.3%', 'B. 9.8%', 'C. 5.0%', 'D. 7.7%'], "correct": 1}, 

    { "text": 'A furnace is fired with sub bituminous B\r\ncoal containing 10.3% moisture, 34% VCM\r\nand 7.7% ash. It is also known to contain\r\n1.2% N and 1.57% S. Its calorific value is 22\r\nMJ/kg. Calculate its: % Fixed carbon',  "options": ['A. 55%', 'B. 37%', 'C. 48%', 'D.  62%'], "correct": 2}, 
    { "text": 'A furnace is fired with sub bituminous B\r\ncoal containing 10.3% moisture, 34% VCM\r\nand 7.7% ash. It is also known to contain\r\n1.2% N and 1.57% S. Its calorific value is 22\r\nMJ/kg. Calculate its: % Combined water',  "options": ['A. 22.5%', 'B.  10.7%', 'C.  18.5%', 'D. 35.9%'], "correct": 0}, 
    { "text": 'A furnace is fired with sub bituminous B\r\ncoal containing 10.3% moisture, 34% VCM\r\nand 7.7% ash. It is also known to contain\r\n1.2% N and 1.57% S. Its calorific value is 22\r\nMJ/kg. Calculate its: % Oxygen',  "options": ['A. 29%', 'B. 40%', 'C. 38%', 'D. 15%'], "correct": 0}, 
    { "text": 'A furnace is fired with sub bituminous B\r\ncoal containing 10.3% moisture, 34% VCM\r\nand 7.7% ash. It is also known to contain\r\n1.2% N and 1.57% S. Its calorific value is 22\r\nMJ/kg. Calculate its: % Combined water in VCM',  "options": ['A.  55%', 'B. 44%', 'C. 66%', 'D. 33%'], "correct": 2}, 
    { "text": 'A furnace is fired with sub bituminous B\r\ncoal containing 10.3% moisture, 34% VCM\r\nand 7.7% ash. It is also known to contain\r\n1.2% N and 1.57% S. Its calorific value is 22\r\nMJ/kg. Calculate its: Calorific Value of VCM.',  "options": ['A. 12 MJ/kg', 'B. 17 MJ/kg', 'C. 15 MJ/kg', 'D. 10 MJ/kg'], "correct": 1}, 

    { "text": 'A furnace is fired with high\r\nvolatile A bituminous coal whose\r\nultimate analysis shows 75.2% C,\r\n5.19% H, 8.72% 0, 1.5% N, 7.8%\r\nash and 1.6% S. 60% excess air is\r\nsupplied. Assume CO to CO₂ ratio\r\nof 0.175. The stack gas leaves at\r\n300°C, 740 torrs. Calculate: The % water in the complete\r\nanalysis of the stack gas if air is\r\nsupplied at 28C, 100 kPa and\r\nessentially dry.',  "options": ['A. 2.06%', 'B. 5.90%', 'C. 3.12%', 'D. 4.47%'], "correct": 3}, 
    { "text": 'A furnace is fired with high\r\nvolatile A bituminous coal whose\r\nultimate analysis shows 75.2% C,\r\n5.19% H, 8.72% 0, 1.5% N, 7.8%\r\nash and 1.6% S. 60% excess air is\r\nsupplied. Assume CO to CO₂ ratio\r\nof 0.175. The stack gas leaves at\r\n300°C, 740 torrs. Calculate:  The calorific value of the coal.',  "options": ['A. 28 MJ/kg', 'B. 25 MJ/kg', 'C.  31 MJ/kg', 'D. 39 MJ/kg'], "correct": 2}, 

    { "text": 'A boiler is fired with coal containing 72.63% C, 14% ash, 1.6%\r\nand 1.2% S burnt under conditions that the elimination\r\ncombustibles from the refuse is complete. The air enters the\r\nfurnace at 25°C, 760 mmHg with 80% RH. The flue gases go to the\r\nstack at 280°C and 110 kPa. The average flue gas Orsat analysis is\r\n8.41% CO₂, 2.52% CO, 0.76% H2 and 9.86% 02. Calculate the % excess\r\nN\r\nof\r\nair. ',  "options": ['A. 65%', 'B. 79%', 'C. 58%', 'D. 83%'], "correct": 0}, 

    { "text": 'A high volatile B bituminous coal\r\nanalyzing 22% VCM, 64% FC, 4% M,\r\n1.4% N and 1.6% S has a calorific\r\nvalue of 32.5 MJ/kg. It is burned in\r\nexcess air supplied essentially dry at\r\n28°C and 1 atm. The dry stack gases\r\nleave at 250°C, 740 mmHg and\r\ncontain 8.37% CO2, 4.19% CO and\r\n2.51% H2. Calculate: The % excess 02',  "options": ['A. 38%', 'B. 40%', 'C. 55%', 'D. 62%'], "correct": 1}, 
    { "text": 'A high volatile B bituminous coal\r\nanalyzing 22% VCM, 64% FC, 4% M,\r\n1.4% N and 1.6% S has a calorific\r\nvalue of 32.5 MJ/kg. It is burned in\r\nexcess air supplied essentially dry at\r\n28°C and 1 atm. The dry stack gases\r\nleave at 250°C, 740 mmHg and\r\ncontain 8.37% CO2, 4.19% CO and\r\n2.51% H2. Calculate: The % N₂ in the complete Orsat\r\nanalysis of the stack gas',  "options": ['A. 72%', 'B. 89%', 'C. 76%', 'D. 80%'], "correct": 2}

]